version: "2.1"
services:
    nginx-auth:
        build: .
        container_name: nginx-http-auth
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./config:/config
        ports:
            - 8080:80
            #- 443:443
        restart: unless-stopped
