#!/usr/bin/with-contenv bash

DEFAULT_WATCH=( \
    /config/conf/nginx.conf \
    /config/conf/sites.conf \
)

for i in ${DEFAULT_WATCH[@]}; do
    if [ -f "${i}" ] || [ -d "${i}" ]; then
        echo "${i}"
        ACTIVE_WATCH="${ACTIVE_WATCH} ${i}"
    fi
done

for i in $(echo "$WATCHLIST" | tr "|" " "); do
    if [ -f "${i}" ] || [ -d "${i}" ]; then
        echo "${i}"
        ACTIVE_WATCH="${ACTIVE_WATCH} ${i}"
    fi
done

function wait_for_changes {
    inotifywait -rq \
        --event close_write \
        ${ACTIVE_WATCH}
}

while wait_for_changes; do
    if /usr/sbin/nginx -c /config/conf/nginx.conf -t; then
        echo "Changes to nginx config detected and the changes are valid, reloading nginx"
        /usr/sbin/nginx -c /config/conf/nginx.conf -s reload
    else
        echo "Changes to nginx config detected but the changes are not valid, skipping nginx reload. Please fix your config."
    fi  
done
